### ISSUE TITLE
wiki 子页面在 vercel 上报 404 错误

### ISSUE THREAD

**Issue by chiyuki0325** [YidaozhanYa/hexo-theme-stellaris#11]

**Comment by taranakineko** [comment]
Vercel 和 CloudFlare 对于省略 `.html` 的访问时处理方式不同，前者必须加上 `.html` 才能正常访问（除非是默认的 `index.html` ）否则会报 404
而 cf 忽略掉 `.html` 也能正常访问（

---

唉没想到时至今日还会踩到这坑（
以及 vercel 上能访问的 `https://blog.chyk.ink/archives`，在 cf 上访问会给你加个 `/` 变成 `https://ydz-blog.pages.dev/archives/`
~~强迫症人狂喜（划去~~

---

对了，反代似乎没写好，导致 wiki 页的 start 数为 0 了，CORS 的问题（（

**Comment by taranakineko** [comment]
以及建议这 issues Pin 上去（bushi（自己不敢 pin（
毕竟不是主题的锅，只能算没考虑到多平台部署以及各平台之间的细节差异

**Comment by chiyuki0325** [comment]
不是主题的锅，也不是 Hexo 的锅，更不是多平台部署的锅。
详见 https://github.com/chiyuki0325/blog/commit/d43906382873bd5ed2fac4f91cb56e586356b36c ，把 Wiki 文章移动到对应的 index.md 即可。
